# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - bug
          - bugfix
    - title: 🛠️ Bug Fix
      labels:
        - bug
        - bugfix
    - title: 📦 Dependencies
      labels:
        - dependencies
