name: Submit an Issue
description: Open an issue to report a bug or request a feature.
title: "[Issue]: <Please replace with a clear and concise title>"

body:
  - type: markdown
    attributes:
      value: |
        ## 📍 Please confirm which version you're using
        
        This repository supports the **standalone Docker container** version of onstar2mqtt.
        
        **You're in the right place if you:**
        - Running onstar2mqtt with `docker run` or `docker-compose`
        - Using direct Node.js installation
        - Running onstar2mqtt outside of Home Assistant
        
        **If you're using the Home Assistant Add-on version**, please submit your issue at [BigThunderSR/homeassistant-addons-onstar2mqtt](https://github.com/BigThunderSR/homeassistant-addons-onstar2mqtt/issues/new) instead — that repo is specifically for the Home Assistant add-on.
        
        ---
        
        For general questions or help, please use the [Discussions](https://github.com/BigThunderSR/onstar2mqtt/discussions) tab.

  - type: checkboxes
    id: version-confirmation
    attributes:
      label: "Version Confirmation"
      description: "Please confirm which version you're using"
      options:
        - label: "I'm using the standalone Docker/Node.js version (not the Home Assistant add-on)"
          required: true

  - type: input
    id: version
    attributes:
      label: OnStar2MQTT Version
      description: Which version are you using? (e.g., 2.5.0) - Check package.json or Docker image tag
      placeholder: e.g., 2.5.0
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type of Issue
      description: What type of issue are you reporting?
      multiple: false
      options:
        - --- Please select an option ---
        - Bug (regression - was working before)
        - Bug (never worked)
        - Feature Request / Enhancement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: A clear and concise description of what the issue is.
      placeholder: Describe the issue
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior (**Note: these are generic steps, please replace with your own steps**):

        1. Start '...'
        2. Try '...'
        3. Do '...'
        4. See error
      placeholder: Steps to reproduce the behavior
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Expected result
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Sanitized Log Output
      description: |
        If applicable, add sanitized log output to help explain your problem.
        **IMPORTANT: Remove VIN, username, password, PIN, tokens, and location data before posting.**
      placeholder: Sanitized log output

  - type: textarea
    id: getvehicledetails_output
    attributes:
      label: Output from Running "GetVehicleDetails" Command
      description: |
        For sensor and command errors/issues, please provide the output from running the `GetVehicleDetails` command (remove any sensitive information).
      placeholder: Output from running "GetVehicleDetails" command

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Add screenshots

  - type: markdown
    attributes:
      value: |
        ## Environment Information

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running OnStar2MQTT?
      multiple: false
      options:
        - --- Please select an option ---
        - Docker Container (standalone)
        - Docker Compose
        - Direct Node.js Installation
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: e.g. Windows, macOS, Linux
      placeholder: Operating System
    validations:
      required: true

  - type: input
    id: node_version
    attributes:
      label: Node.js Version (if using Direct Node.js Installation)
      description: Only required for direct Node.js installations - e.g. 18.20.0, 20.11.0, 22.x
      placeholder: Node.js Version

  - type: input
    id: npm_version
    attributes:
      label: npm Version (if using Direct Node.js Installation)
      description: Only required for direct Node.js installations - e.g. 6.14.13, 10.2.4
      placeholder: npm Version

  - type: input
    id: other_environment_details
    attributes:
      label: Other Environment Details
      description: Any other relevant environment details (e.g., Docker version, architecture, reverse proxy)
      placeholder: Other environment details

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Additional context
